version: '3'
services:
    webservice:
        container_name: lodex-webservice
        build:
            context: .
            args:
                - http_proxy
                - https_proxy
        image: inistcnrs/lodex-webservice:0.0.0
        environment:
            - http_proxy
            - https_proxy
        ports:
            - "31976:31976"
